import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../components/ui/accordion";

const Faqs = () => {
  const [openIndex, setOpenIndex] = React.useState<number>(0);
  const faqData = [
    {
      question: "What is Trust AI?",
      answer:
        "Trust AI is a revolutionary blockchain project integrating artificial intelligence into smart contracts. It aims to redefine trust and security in the crypto space.",
    },
    {
      question: "What is Trust AI Token?",
      answer:
        "Trust AI Token (TRT) is the native utility token of the Trust AI platform, empowering users to engage in various activities, including staking and NFT transactions.",
    },
    {
      question: "How to contact the Trust AI Team?",
      answer:
        "For direct communication with the Trust AI team, you can reach out through our official channels on Discord, Telegram, or via email at (contact@trust-ai.io).",
    },
    {
      question: "What is the bonus for staking?",
      answer:
        "Stakers enjoy competitive bonuses based on the duration of their staking commitment. The longer you stake, the higher the bonus, creating an incentivized environment for long-term participation.",
    },
    {
      question: "Will stakers benifit from Generated Revenues?",
      answer:
        "Absolutely! Stakers are entitled to a share of the revenues generated by the Trust AI platform. This distribution mechanism ensures that our community actively participates in the success of the project.",
    },
    {
      question: "Where to buy Trust AI Token?",
      answer:
        "Trust AI tokens (TRT) are available for purchase on PancakeSwap, a decentralized exchange built on the Binance Smart Chain. Visit PancakeSwap and trade BNB for TRT to join the Trust AI community.",
    },
  ];
  return (
    <div className="max-w-[1440px] sm:w-[60%] mx-auto py-16 sm:px-0 px-6">
      <div className="text-white text-4xl text-center my-8">FAQS</div>
      <Accordion type="single" collapsible>
        {faqData.map((faq, index) => (
          <AccordionItem
            value={faq.question}
            key={faq.question}
            onClick={() => setOpenIndex(index)}
          >
            <AccordionTrigger
              className={`${
                index === openIndex ? "text-[#c27803] " : `text-white`
              } text-xl text-left gap-4`}
            >
              {faq.question}
            </AccordionTrigger>
            <AccordionContent className="text-[#6b7280] text-xl">
              {faq.answer}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
};

export default Faqs;
